name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://tinyurl.com/FeatureDiscovery
version: 0.5.1
authors: 
  - ayalma <alimohammadi7117@gmail.com>
  - creativecreatorormaybenot <creativecreatorormaybenot@gmail.com>
  - axel-op
homepage: https://github.com/ayalma/feature_discovery

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
