name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://tinyurl.com/FeatureDiscovery
version: 0.8.0
authors:
  - ayalma <alimohammadi7117@gmail.com>
  - creativecreatorormaybenot <19204050+creativecreatorormaybenot@users.noreply.github.com>
  - axel-op <49279289+axel-op@users.noreply.github.com>
homepage: https://github.com/ayalma/feature_discovery

environment:
  # This should match the Flutter stable SDK constraint.
  # See https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml.
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  shared_preferences: ^0.5.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: 1.9.0

dependency_overrides:
  # TODO(creativecreatorormaybenot): Remove when Pedantic is updated in flutter_test.
  pedantic: 1.9.0
